-- Lecture 5 Tasks
-----------------------------------
-- Task 1:

SELECT AVG(SALARY) FROM EMPLOYEES;

------------------------------------
SELECT COUNT(*) FROM EMPLOYEES;

------------------------------------
SELECT MAX(SALARY) FROM EMPLOYEES;

------------------------------------
SELECT MIN(SALARY) FROM EMPLOYEES;

------------------------------------
SELECT SUM(SALARY) FROM EMPLOYEES;

------------------------------------
SELECT DEPARTMENT_ID, AVG(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID;

------------------------------------
SELECT JOB_ID, COUNT(EMPLOYEE_ID) FROM EMPLOYEES GROUP BY JOB_ID;

------------------------------------
SELECT DEPARTMENT_ID , SUM(SALARY) AS Total_Salary FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING SUM(SALARY) > 50000;

------------------------------------
SELECT AVG(NVL(COMMISSION_PCT, 0)) FROM EMPLOYEES;

SELECT AVG(COMMISSION_PCT) FROM EMPLOYEES  WHERE COMMISSION_PCT IS NOT NULL;

------------------------------------
SELECT COUNT(EMPLOYEE_ID) FROM EMPLOYEES WHERE SALARY > 10000;

------------------------------------
SELECT JOB_ID, MIN(SALARY) , MAX(SALARY) FROM EMPLOYEES GROUP BY JOB_ID;

------------------------------------
SELECT MANAGER_ID, SUM(SALARY) FROM EMPLOYEES GROUP  BY MANAGER_ID;

------------------------------------
SELECT DEPARTMENT_ID, JOB_ID, SUM(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID, jOB_ID;

------------------------------------
SELECT JOB_ID, COUNT(EMPLOYEE_ID) FROM EMPLOYEES GROUP BY JOB_ID HAVING COUNT(EMPLOYEE_ID) > 5;

------------------------------------
SELECT DEPARTMENT_ID, COUNT(EMPLOYEE_ID), AVG(SALARY), MIN(SALARY), MAX(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID;

------------------------------------
SELECT DEPARTMENT_ID FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING AVG(SALARY) > 8000 AND COUNT(EMPLOYEE_ID) < 10;

------------------------------------
SELECT DEPARTMENT_ID, SUM(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY SUM(SALARY) DESC FETCH FIRST 1 ROW ONLY;

------------------------------------

SELECT DEPARTMENT_ID, SUM(SALARY) AS TOTAL_SALARY, AVG(SALARY) AS AVERAGE_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT_ID;